AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'example/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - '*.gemspec'


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

inherit_gem:
  rubocop-discourse: default.yml
